# Generated by Django 3.2b1 on 2021-03-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0056_extend_configcontext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customlink',
            old_name='text',
            new_name='link_text',
        ),
        migrations.RenameField(
            model_name='customlink',
            old_name='url',
            new_name='link_url',
        ),
        migrations.AlterField(
            model_name='customlink',
            name='new_window',
            field=models.BooleanField(default=False),
        ),
    ]
