# Generated by Django 3.2b1 on 2021-03-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0054_standardize_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectchange',
            old_name='object_data',
            new_name='postchange_data',
        ),
        migrations.AlterField(
            model_name='objectchange',
            name='postchange_data',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='objectchange',
            name='prechange_data',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
